services:
  - type: web
    name: resume-screener-app
    env: python
    plan: free  # or choose a paid plan
    buildCommand: pip install -r requirements.txt
    startCommand: sh -c "streamlit run app.py --server.port=$PORT"
